from hest import iter_hest
import pandas as pd
from scanpy import AnnData
import logging 


logger = logging.getLogger(__name__)
'''
    Method to join Cluster annotation generated by the loupe browser to 
    hest1k anndata
'''
def join_annotation(adata:AnnData, annotation:pd.DataFrame):
    return pd.concat([adata.obs,annotation], join="outer", axis = 1)

def join_annotators(annotators:list[str],index:str = "Barcode"):
    logging.info(annotators)   
    annotations = pd.concat(
        [
            pd.read_csv(annotator,index_col=index) for annotator in annotators
        ], join = "inner", axis = 1, 
    )
    annotations.columns = [annotator.name for annotator in annotators]
    return annotations
